### ISSUE TITLE
502 error when accessing the demo

### ISSUE THREAD

**Issue by rmacklin** [google/git-appraise-web#24]
Hello there,

I came across this project and wanted to take a look at the demo:
https://github.com/google/git-appraise-web/blob/74eabe5c33762ccd94e7d3354bfcbe1ca86543f4/README.md#L7

but it doesn't seem to be working:

![image](https://user-images.githubusercontent.com/1863540/108797073-2fc8a480-753f-11eb-9a67-ad6f628ed508.png)

**Comment by ojarjur** [comment]
Thanks for pointing this out. The hosted live demo has been taken down.

I'll update the README to no longer point to it.
